export const MenuItems=[
    
    {
        title:'Vodka',
        url:'/vodka',
    },
    {
        title:'Gin',
        url:'/gin',
    },
    {
        title:'Tequila',
        url:'/tequila',
    },
    {
        title:'Whiskey',
        url:'/whiskey',
    },
    {
        title:'Brandy',
        url:'/brandy',
    },
    {
        title:'Rum',
        url:'/rum',
    },
    {
        title:'Vermouth',
        url:'/vermouth',
    },
]